server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: admin-server
  datasource: #springboot会直接在容器中构建一个dataSource供我们使用。
    url: jdbc:mysql://localhost:3306/spring_cloud_hawk?serverTimezone=UTC
    username: hawk
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis: #Redis 配置
    database: 0  #Redis数据库索引(默认为0)
    host: 127.0.0.1 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    password: #Redis服务器连接密码(默认为空)
    timeout: 60s # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    jedis: # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
      pool:
        max-active:  20 #连接池最大连接数(使用负值表示没有限制)
        max-idle: 10 #连接池最大空闲连接数
        max-wait: 100s #连接池最大阻塞等待时间(使用负值表示没有限制)
        min-idle: 5 #连接池最小空闲连接

mybatis:
  type-aliases-package: com.hawk.admin.adminserver.entity
  mapper-locations: com.hawk.admin.adminserver.mapper/*.xml